version: "3.9"  
services:
  get-cids-service:
    image: get-cids 
    ports:
      - "3000:3000"  
    deploy:
      replicas: 3  # Number of container replicas (instances)
      resources:
        limits:
          cpus: '0.5' 
          memory: 2048M 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3